name: Deploy to Server

on:
  push:
    branches:
      - nielad-patch-1 # or any branch you use for deployment

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Specifies that this job runs on a self-hosted runner

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Build Docker Image
      run: docker build -t github-actions-test-image .

    - name: Run Docker Container
      run: docker run -d --name github-actions-test-container github-actions-test-image


